package com.nyanyaww.GUI;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;

/**
 * @author nyanyaww
 * @program modbus
 * @description
 * @create 2019-06-18 16:47
 **/
public class ServerGUI {
    private JPanel main;
    private JPanel top;
    private JPanel bottom;
    private JPanel center;
    private JPanel left;
    private JComboBox chooseAddrComboBox;
    private JButton connectButton;
    private JLabel help;
    private JTextField sendTextField;
    private JButton sendButton;
    private JButton closeButton;
    private JTextField textField1;
    private JLabel ipLabel;
    private JLabel portLabel;


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        main = new JPanel();
        main.setLayout(new BorderLayout(10, 10));
        main.setAlignmentX(1.0f);
        main.setAlignmentY(1.0f);
        main.setBorder(BorderFactory.createTitledBorder(null, "modbus主机", TitledBorder.CENTER, TitledBorder.DEFAULT_POSITION));
        top = new JPanel();
        top.setLayout(new GridBagLayout());
        main.add(top, BorderLayout.NORTH);
        top.setBorder(BorderFactory.createTitledBorder("top"));
        final JPanel spacer1 = new JPanel();
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.ipadx = 1;
        top.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.VERTICAL;
        top.add(spacer2, gbc);
        help = new JLabel();
        help.setText("帮助");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        top.add(help, gbc);
        bottom = new JPanel();
        bottom.setLayout(new BorderLayout(0, 0));
        main.add(bottom, BorderLayout.SOUTH);
        bottom.setBorder(BorderFactory.createTitledBorder("发送区"));
        sendTextField = new JTextField();
        sendTextField.setText("");
        bottom.add(sendTextField, BorderLayout.CENTER);
        sendButton = new JButton();
        sendButton.setText("发送");
        bottom.add(sendButton, BorderLayout.EAST);
        center = new JPanel();
        center.setLayout(new GridBagLayout());
        main.add(center, BorderLayout.CENTER);
        center.setBorder(BorderFactory.createTitledBorder("显示区"));
        final JPanel spacer3 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        center.add(spacer3, gbc);
        final JPanel spacer4 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.VERTICAL;
        center.add(spacer4, gbc);
        final JScrollPane scrollPane1 = new JScrollPane();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.ipadx = 300;
        gbc.ipady = 300;
        center.add(scrollPane1, gbc);
        left = new JPanel();
        left.setLayout(new GridBagLayout());
        main.add(left, BorderLayout.WEST);
        left.setBorder(BorderFactory.createTitledBorder(null, "连接", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, this.$$$getFont$$$(null, -1, -1, left.getFont()), new Color(-4473925)));
        final JPanel spacer5 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 4;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        left.add(spacer5, gbc);
        chooseAddrComboBox = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        defaultComboBoxModel1.addElement("127.0.0.1");
        chooseAddrComboBox.setModel(defaultComboBoxModel1);
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        left.add(chooseAddrComboBox, gbc);
        ipLabel = new JLabel();
        Font ipLabelFont = this.$$$getFont$$$(null, -1, -1, ipLabel.getFont());
        if (ipLabelFont != null) ipLabel.setFont(ipLabelFont);
        ipLabel.setRequestFocusEnabled(true);
        ipLabel.setText("ip地址");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        left.add(ipLabel, gbc);
        portLabel = new JLabel();
        portLabel.setText("端口号");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        left.add(portLabel, gbc);
        textField1 = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        left.add(textField1, gbc);
        closeButton = new JButton();
        closeButton.setText("断开");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        left.add(closeButton, gbc);
        final JPanel spacer6 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.VERTICAL;
        left.add(spacer6, gbc);
        connectButton = new JButton();
        connectButton.setText("连接");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        left.add(connectButton, gbc);
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        return new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return main;
    }

    public static void main(String[] args) {
        JFrame frame = new JFrame("ServerGUI");
        frame.setContentPane(new ServerGUI().main);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

}
